# Generated by Django 4.2.30 on 2026-08-26 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Roll number / unique student identifier used for enrollment.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive students are excluded from recognition and reporting.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Present"), ("LATE", "Late")],
                        default="PRESENT",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Recognition confidence percentage (0-100) at the moment attendance was marked.",
                        null=True,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-marked_at"],
                "indexes": [
                    models.Index(fields=["date"], name="attendance__date_61f2e1_idx"),
                    models.Index(
                        fields=["student", "date"],
                        name="attendance__student_76a8d7_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "date"), name="unique_attendance_per_student_per_day"
            ),
        ),
    ]
